# Generated by Django 6.0.3 on 2026-03-17 08:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('steps_count', models.IntegerField(default=0)),
                ('hours_seated', models.FloatField(default=0.0)),
                ('apt_correctives_done', models.BooleanField(default=False)),
                ('water_ml', models.IntegerField(default=0)),
                ('is_rest_day', models.BooleanField(default=False)),
                ('planned_workout', models.CharField(blank=True, max_length=50)),
                ('soreness_profile', models.JSONField(default=dict)),
                ('whey_scoops', models.FloatField(default=0.0)),
                ('creatine_g', models.FloatField(default=0.0)),
                ('took_multivitamin', models.BooleanField(default=False)),
                ('took_fish_oil', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meal_type', models.CharField(max_length=20)),
                ('raw_input_text', models.TextField(blank=True)),
                ('calories', models.IntegerField(default=0)),
                ('protein_g', models.IntegerField(default=0)),
                ('is_high_sodium', models.BooleanField(default=False)),
                ('is_high_sugar', models.BooleanField(default=False)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='core.dailylog')),
            ],
        ),
    ]
