# Generated by Django 6.0.3 on 2026-03-22 16:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('steps_count', models.IntegerField(default=0)),
                ('hours_seated', models.FloatField(default=0.0)),
                ('apt_correctives_done', models.BooleanField(default=False)),
                ('water_ml', models.IntegerField(default=0)),
                ('is_rest_day', models.BooleanField(default=False)),
                ('planned_workout', models.CharField(blank=True, max_length=50)),
                ('soreness_profile', models.JSONField(default=dict)),
                ('whey_scoops', models.FloatField(default=0.0)),
                ('creatine_g', models.FloatField(default=0.0)),
                ('took_multivitamin', models.BooleanField(default=False)),
                ('took_fish_oil', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meal_type', models.CharField(max_length=20)),
                ('raw_input_text', models.TextField(blank=True)),
                ('calories', models.IntegerField(default=0)),
                ('protein_g', models.IntegerField(default=0)),
                ('carbs_g', models.IntegerField(default=0)),
                ('fats_g', models.IntegerField(default=0)),
                ('meal_summary', models.CharField(blank=True, max_length=140)),
                ('is_high_sodium', models.BooleanField(default=False)),
                ('is_high_sugar', models.BooleanField(default=False)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='core.dailylog')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_years', models.PositiveSmallIntegerField(default=22)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('body_fat_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Lightly Active'), ('moderate', 'Moderately Active'), ('active', 'Very Active'), ('athlete', 'Athlete')], default='moderate', max_length=12)),
                ('goal', models.CharField(choices=[('cut', 'Cut'), ('maintain', 'Maintain'), ('gain', 'Gain')], default='cut', max_length=10)),
                ('target_deficit_kcal', models.IntegerField(default=400)),
                ('gemini_api_key', models.CharField(blank=True, default='', max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailylog',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_log_per_user_date'),
        ),
    ]
