# Generated by Django 6.0.3 on 2026-03-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_coachmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_years', models.PositiveSmallIntegerField(default=22)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('body_fat_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Lightly Active'), ('moderate', 'Moderately Active'), ('active', 'Very Active'), ('athlete', 'Athlete')], default='moderate', max_length=12)),
                ('goal', models.CharField(choices=[('cut', 'Cut'), ('maintain', 'Maintain'), ('gain', 'Gain')], default='cut', max_length=10)),
                ('target_deficit_kcal', models.IntegerField(default=400)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
